---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-robot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-example-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: tekton-robot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-example-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-robot
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: image-build-trigger
  namespace: default
spec:
  params:
  - name: git_sha
    default: ""
  - name: git_revision
    default: ""
  - name: git_url
    default: ""
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: build-image-
      namespace: default
    spec:
      taskRunTemplate:
        podTemplate:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            fsGroup: 65532
        serviceAccountName: default
      params:
        - name: GIT_REPOSITORY
          value: $(tt.params.git_url)
        - name: GIT_REPOSITORY_BRANCH
          value: main
        - name: IMAGE_NAME
          value: quay.io/kubealex/centos-bootc-demo
        - name: IMAGE_TAGS
          value: latest app $(tt.params.git_revision)
        - name: COSIGN_GENERATE_KEYS
          value: false
      pipelineRef:
        name: centos-bootc-image-build
      timeouts:
        pipeline: 1h0m0s
      workspaces:
        - name: main-workspace
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
              storageClassName: ceph-filesystem
        - name: registry-creds
          secret:
            secretName: container-auth
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: bootc-image-builder-trigger
  namespace: default
spec:
  params:
  - name: git_sha
    default: ""
  - name: git_revision
    default: ""
  - name: git_url
    default: ""
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: bootc-image-builder-
        namespace: default
      spec:
        timeouts:
          pipeline: "3h0m0s"
          tasks: "1h0m0s"
          finally: "0h0m20s"
        pipelineRef:
          name: bootc-end-to-end-pipeline
        params:
          - name: SOURCE_IMAGE_NAME
            value: quay.io/kubealex/centos-bootc-demo
          - name: SOURCE_IMAGE_TAG
            value: latest
          - name: GIT_REPOSITORY
            value: $(tt.params.git_url)
          - name: GIT_REPOSITORY_BRANCH
            value: main
          - name: IMAGE_NAME
            value: quay.io/kubealex/centos-bootc-demo
          - name: IMAGE_TAGS
            value: latest app $(tt.params.git_revision)
          - name: COSIGN_GENERATE_KEYS
            value: true
          - name: KUBEVIRT_IMAGE_BUILD
            value: true
          - name: LOGICALLY_BOUND_IMAGES
            value: quay.io/kubealex/tailwind-pos:latest
        podTemplate:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
        taskRunSpecs:
          - pipelineTaskName: git-clone
            podTemplate:
              securityContext:
                fsGroup: 65532
        # taskRunTemplate:
        #   podTemplate:
        #     securityContext:
        #       runAsNonRoot: false
        #       runAsUser: 0
        #       fsGroup: 65532
        #   serviceAccountName: default
        workspaces:
          - name: main-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
                storageClassName: ceph-filesystem
          - name: registry-creds
            secret:
              secretName: container-auth
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: image-build-binding
spec:
  params:
  - name: git_sha
    value: $(body.sha)
  - name: git_revision
    value: $(body.ref)
  - name: git_url
    value: $(body.repository.clone_url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: image-build-listener
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: image-build-initiator
      bindings:
      - ref: image-build-binding
      template:
        ref: bootc-image-builder-trigger
      interceptors:
      - ref:
          name: cel
        params:
        - name: filter
          value: body['ref'].contains("qcow")
    - name: image-build-initiator
      bindings:
      - ref: image-build-binding
      template:
        ref: image-build-trigger
      interceptors:
      - ref:
          name: cel
        params:
        - name: filter
          value: "!(body['ref'].contains('qcow'))"
